version: "3"

services:
  hub:
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
      args:
        JUPYTERHUB_VERSION: latest
    restart: always
    image: jupyterhub
    container_name: jupyterhub
    depends_on:
      - traefik
    networks:
      - jupyterhub-network
    volumes:
      # The JupyterHub configuration file
      - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "jupyterhub-data:/data"
    ports:
      - "8000:8000"
    environment:
      # This username will be a JupyterHub admin
      JUPYTERHUB_ADMIN: admin
      # All containers will join this network
      DOCKER_NETWORK_NAME: jupyterhub-network
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: jupyternotebook
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: /home/jovyan/work
    labels:
      - "traefik.enable=true"
      # TODO: fill in the website
      - "traefik.http.routers.hub.rule=Host(`igor0.example.pub`) && PathPrefix(`/jupyter`)"
      - "traefik.http.routers.hub.entrypoints=websecure"
      - "traefik.http.routers.hub.tls=true"
      - "traefik.http.routers.hub.tls.certresolver=myresolver"

  
  traefik:
    image: "traefik:v3.0"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # TODO: fill in the email
      - "--certificatesresolvers.myresolver.acme.email=example@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8081:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - jupyterhub-network

volumes:
  jupyterhub-data:

networks:
  jupyterhub-network:
    name: jupyterhub-network


# Playbook
# docker build -f Dockerfile.jupyternotebook . -t jupyternotebook --ssh default && docker compose up --build

# The https and TLS need their own domain and potentail certificate refresh setup.

# $ cat /etc/docker/daemon.json
# {
# "runtimes": {
#   "nvidia": {
#     "args": [],
#     "path": "nvidia-container-runtime"
#     }
#     },
#     "dns": ["8.8.8.8", "8.8.4.4"],
#     "default-runtime": "nvidia"
# }
